[Issue #732] support one table scan
pixelsdb/pixels pull request #750
Opened 2024-10-09 03:52 UTC by huasiy

2024-10-09 03:52 UTC, huasiy commented
Resolves #732

2024-10-09 08:25 UTC, huasiy commented
![image](https://github.com/user-attachments/assets/a6148c71-083f-41a2-85bb-ddae53e92026)

2024-10-09 08:26 UTC, huasiy commented
![image](https://github.com/user-attachments/assets/9b877c00-d2ff-4a04-916e-9e4868bfb12b)

2024-10-10 04:04 UTC, bianhq requested changes

2024-10-10 04:04 UTC, bianhq commented on pixels-turbo/pixels-worker-common/src/main/java/io/pixelsdb/pixels/worker/common/BaseScanStreamWorker.java
> +                    ScanInput.generateOutputPaths(outputFolder, 100));
Do not hardcode the numSplits.

2024-10-10 09:36 UTC, huasiy commented on pixels-turbo/pixels-worker-vhive/pom.xml
> +                <artifactId>maven-shade-plugin</artifactId>
Yes. Refer to issue #703.

2024-10-10 15:50 UTC, bianhq commented on pixels-turbo/pixels-worker-vhive/pom.xml
> +                <artifactId>maven-shade-plugin</artifactId>
OK

2024-10-11 08:38 UTC, bianhq requested changes

2024-10-11 08:38 UTC, bianhq commented on pixels-common/src/main/resources/pixels.properties
> +executor.worker.coordinator.ip=10.168.4.4
We already have `worker.coordinate.server.host` and `worker.coordinate.server.port` in pixels.properties.

2024-10-11 08:38 UTC, bianhq commented on pixels-turbo/pixels-invoker-vhive/src/main/java/io/pixelsdb/pixels/invoker/vhive/ScanStreamInvokerProvider.java
> +public class ScanStreamInvokerProvider implements InvokerProvider
use `@author` and `@create`.

2024-10-11 08:47 UTC, bianhq approved these changes
LGTM.

2024-10-11 08:48 UTC, merged