[Issue #737] Feature/add hidden column
pixelsdb/pixels pull request #754
Opened 2024-10-11 01:48 UTC by gengdy1545

2024-10-11 11:45 UTC, gengdy1545 commented
When loading data, a timestamp is assigned and grows normally (assuming it grows to k), but the timestamp corresponding to the query executed in trino-cli does not grow on the basis of k, so no data is read.

2024-10-12 09:22 UTC, bianhq requested changes

2024-10-13 08:53 UTC, gengdy1545 commented on pixels-core/src/main/java/io/pixelsdb/pixels/core/vector/ColumnVector.java
> +public abstract class ColumnVector implements AutoCloseable, Cloneable
Shallow copy for BinaryColumnVector type, read to columnVectors affects resultRowBatch.cols[i].writeIndex (PixelsRecordReaderImpl.java line1066). Haven't verified if it's a bug yet.

2024-10-23 13:19 UTC, bianhq requested changes

2024-10-23 13:19 UTC, bianhq commented on pixels-core/src/main/java/io/pixelsdb/pixels/core/reader/PixelsRecordReaderImpl.java
> +        this.includeHiddenColumn = this.timestamp != -1L;
this.timestamp != -1L is not secure.

2024-10-23 13:19 UTC, bianhq commented on pixels-example/src/main/java/io/pixelsdb/pixels/example/core/TestColumnReader.java
> +package io.pixelsdb.pixels.example.core;
Add license header.

2024-10-23 13:19 UTC, bianhq commented on proto/pixels.proto
> +    // row group statistics for hidden timestamp columns
It is better to add the fields for hidden columns at the end of the Footer. Thus, the new file format will be compatible with the old files.

2024-10-30 15:39 UTC, bianhq approved these changes
LGTM.

2024-10-30 15:43 UTC, merged